# Generated by Django 3.2.4 on 2021-06-22 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='ITN',
            new_name='inn',
        ),
    ]
