# Generated by Django 3.2.4 on 2021-06-22 12:06

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_rename_itn_profile_inn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='check',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
    ]
