# Generated by Django 3.2.4 on 2021-06-23 09:00

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_alter_profile_check'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='inn',
            field=models.CharField(max_length=12, unique=True, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\ \\d+)*\\Z'), code='invalid', message=None), django.core.validators.MinValueValidator(12)]),
        ),
    ]
